#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [ ! -e $SCRIPT_DIR/utilities.jar ]; then
    echo Unable to locate the required '"'utilities.jar'"' file in the '"'$SCRIPT_DIR'"' directory.
    exit 1
fi
java -cp $SCRIPT_DIR/utilities.jar info.rlwhitcomb.cat.Cat $@

