#!/bin/bash
function check_file() {
   grep -v -e "^#.*" -e "^$" $1 >words.txt
   sort words.txt > sort.txt
   diff words.txt sort.txt
   if [ $? -eq 0 ]
   then
      echo The \"$1\" word list is correctly sorted \(`wc <sort.txt -w` words \).
      rm words.txt sort.txt
      return 0
   fi
   echo The \"$1\" word list is NOT sorted correctly!
   return 1
}

for f in $(find info -name "*.txt")
do
  check_file $f
  if [ ! $? -eq 0 ]
  then
    exit 1
  fi
done

