#!/bin/bash
function check_file() {
   grep -v -e "^#.*" -e "^$" $1 >words.txt
   sort words.txt > sort.txt
   diff words.txt sort.txt
   if [ $? -eq 0 ]
   then
      echo The \"$1\" word list is correctly sorted.
      rm words.txt sort.txt
   fi
}

for f in $(find info -name "*.txt")
do
  check_file $f
done

