#!/bin/bash
if [ -z "$1" ]
then
   echo Update a test canon file.
   echo Usage: upc test_name
   exit 1
fi
test=$1
# Note: these options must match the $defaultOptions in calctest
c -nocolors -dir test/files -noseps -sense -utf8 $test | mkcanon > test/canons/${test//[,;]/_}.canon
