#!/bin/bash
if [ -z "$1" ]
then
   echo Update a test canon file.
   echo Usage: upc7 test_name [ canon_name ]
   echo   Note: only works for "e7"
   exit 1
fi
test=$1
if [ -z "$2" ]
then
   canon=$1
else
   canon=$2
fi
# Note: these options must match the $defaultOptions in calctest
c -noOptions -timing -noColors -dir test/files -noSeps -quotes -sense -utf8 -loc en-US -- 'abc' «def» 1 2 3 text -- -define verbose=true $test | mkcanon > test/canons/${canon//[,;]/_}.canon
