#!/bin/bash
NUMBER=43112609
DIGITS=12978189
if [ -e test/data/M$NUMBER.txt.gz ]; then
   cp test/data/M$NUMBER.txt.gz .
   gunz M$NUMBER.txt.gz
fi
lists -single M$NUMBER.txt >ref.txt
c -nocolor -noseps -sense -r ":unl;(2**$NUMBER)-1" >calc.txt
(( count = `wc -c <calc.txt` - 1 ))
diff ref.txt calc.txt
if [[ $? -eq 0 ]] && [[ $count -eq $DIGITS ]]; then
  echo No differences for M$NUMBER \($count digits\)! Calculation is correct.
  rm M$NUMBER.txt ref.txt calc.txt
  exit 0
else
  echo Differences found!
  echo Reference number of digits is $DIGITS, calculated number is $count.
  echo Reference value in "ref.txt", calculated value in "calc.txt"
  echo Original data in "M$NUMBER.txt"
  exit 1
fi
