# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"

    strategy:
      matrix:
        java: [ '11', '17', '21', '24' ]

    steps:
    - uses: actions/checkout@v4
    - name: JDK ${{ matrix.java }} setup
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build with Ant
      run: ./ci-build.sh
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-ubuntu-${{ matrix.java }}
        path: dist/*.log
