# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java 8 CI Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Generate grammars
      run: .\ci-build8-first.bat
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Remaining build
      run: .\ci-build8-second.bat
    - name: Upload build results
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: dist\
